import React, { useState, useEffect } from 'react';
import { Sidebar } from '../components/Sidebar';
import { api } from '../services/api';
import { Sliders, CheckCircle2, Save, ShieldAlert } from 'lucide-react';

export const AdminSettingsPage: React.FC = () => {
  const [universityName, setUniversityName] = useState('Global University of Technology');
  const [confidenceThreshold, setConfidenceThreshold] = useState('0.65');
  const [saving, setSaving] = useState(false);
  const [successMsg, setSuccessMsg] = useState('');

  useEffect(() => {
    async function load() {
      try {
        const res = await api.getConfigs();
        const cfg = res.configs || {};
        if (cfg.UNIVERSITY_NAME) setUniversityName(cfg.UNIVERSITY_NAME);
        if (cfg.AI_CONFIDENCE_THRESHOLD) setConfidenceThreshold(cfg.AI_CONFIDENCE_THRESHOLD);
      } catch {
        // Ignore load error
      }
    }
    load();
  }, []);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    try {
      await api.updateConfigs({
        UNIVERSITY_NAME: universityName,
        AI_CONFIDENCE_THRESHOLD: confidenceThreshold,
      });
      setSuccessMsg('Chatbot parameters updated successfully!');
      setTimeout(() => setSuccessMsg(''), 4000);
    } catch {
      // Ignore save error
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="flex">
      <Sidebar />
      <main className="flex-1 p-8 space-y-8 bg-slate-50 min-h-[calc(100vh-4rem)]">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-navy-900">General Chatbot & Policy Settings</h1>
            <p className="text-xs text-slate-500 mt-1">Configure AI confidence thresholds, system prompts, and institution name</p>
          </div>
        </div>

        {successMsg && (
          <div className="bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs p-4 rounded-xl flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            <span>{successMsg}</span>
          </div>
        )}

        <div className="max-w-2xl bg-white p-8 rounded-3xl border border-slate-200 shadow-sm space-y-6">
          <form onSubmit={handleSave} className="space-y-6">
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">Official University Name</label>
              <input
                type="text"
                required
                value={universityName}
                onChange={(e) => setUniversityName(e.target.value)}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-4 py-2.5 text-sm text-slate-900"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                AI Confidence Escalation Threshold (0.0 to 1.0)
              </label>
              <input
                type="number"
                step="0.05"
                min="0.1"
                max="1.0"
                required
                value={confidenceThreshold}
                onChange={(e) => setConfidenceThreshold(e.target.value)}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-4 py-2.5 text-sm text-slate-900"
              />
              <p className="text-[11px] text-slate-500 mt-1">
                If the match confidence score falls below this value (e.g. 0.65), the bot suggests lodging a ticket.
              </p>
            </div>

            <div className="bg-amber-50 border border-amber-200 p-4 rounded-xl text-xs text-amber-900 space-y-1">
              <div className="font-bold flex items-center gap-1.5">
                <ShieldAlert className="w-4 h-4 text-amber-600" />
                <span>Anti-Hallucination Policy Disclaimer</span>
              </div>
              <p className="text-amber-800">
                Sample university policies are used for demonstration. Official university rules cannot be auto-generated by AI. Administrators can update FAQs anytime.
              </p>
            </div>

            <button
              type="submit"
              disabled={saving}
              className="bg-brand-600 hover:bg-brand-700 text-white font-bold px-6 py-3 rounded-xl text-sm transition shadow-md flex items-center gap-2"
            >
              <Save className="w-4 h-4" />
              <span>{saving ? 'Saving...' : 'Save System Settings'}</span>
            </button>
          </form>
        </div>
      </main>
    </div>
  );
};
